# Introduction

The first test of your new data exploration skills uses data describing crime in the city of Chicago.

Before you get started, run the following cell. It sets up the automated feedback system to review your answers.

**This notebook is an exercise in the [SQL](https://www.kaggle.com/learn/intro-to-sql) course.  You can reference the tutorial at [this link](https://www.kaggle.com/dansbecker/getting-started-with-sql-and-bigquery).**

---

In [17]:
# Set up feedack system
from learntools.core import binder
binder.bind(globals())
from learntools.sql.ex1 import *
print("Setup Complete")

Setup Complete

In [18]:
from google.cloud import bigquery

# Create a "Client" object
client = bigquery.Client()

# Construct a reference to the "chicago_crime" dataset
dataset_ref = client.dataset("chicago_crime", project="bigquery-public-data")

# API request - fetch the dataset
dataset = client.get_dataset(dataset_ref)

Using Kaggle's public dataset BigQuery integration.

Use the next code cell to fetch the dataset.

# Exercises

### 1) Count tables in the dataset

How many tables are in the Chicago Crime dataset?

In [19]:
# Write the code you need here to figure out the answer
tables = client.list_tables(dataset)
for table in tables:
    print(table.table_id)

crime

crime

In [20]:
num_tables = 1  # Store the answer as num_tables and then run this cell

q_1.check()

Correct

In [21]:
num_tables = ____  # Store the answer as num_tables and then run this cell

# Check your answer
q_1.check()

Check: When you've updated the starter code, `check()` will tell you whether your code is correct. You need to update the code that creates variable `num_tables`

For a hint or the solution, uncomment the appropriate line below.

In [22]:
#q_1.hint()
#q_1.solution()

### 2) Explore the table schema

How many columns in the `crime` table have `TIMESTAMP` data?

In [23]:
# Write the code to figure out the answer
tables = dataset_ref.table('crime')
table = client.get_table(tables)
table.schema

[SchemaField('unique_key', 'INTEGER', 'REQUIRED', None, (), None),
 SchemaField('case_number', 'STRING', 'NULLABLE', None, (), None),
 SchemaField('date', 'TIMESTAMP', 'NULLABLE', None, (), None),
 SchemaField('block', 'STRING', 'NULLABLE', None, (), None),
 SchemaField('iucr', 'STRING', 'NULLABLE', None, (), None),
 SchemaField('primary_type', 'STRING', 'NULLABLE', None, (), None),
 SchemaField('description', 'STRING', 'NULLABLE', None, (), None),
 SchemaField('location_description', 'STRING', 'NULLABLE', None, (), None),
 SchemaField('arrest', 'BOOLEAN', 'NULLABLE', None, (), None),
 SchemaField('domestic', 'BOOLEAN', 'NULLABLE', None, (), None),
 SchemaField('beat', 'INTEGER', 'NULLABLE', None, (), None),
 SchemaField('district', 'INTEGER', 'NULLABLE', None, (), None),
 SchemaField('ward', 'INTEGER', 'NULLABLE', None, (), None),
 SchemaField('community_area', 'INTEGER', 'NULLABLE', None, (), None),
 SchemaField('fbi_code', 'STRING', 'NULLABLE', None, (), None),
 SchemaField('x_coordinate', 'FLOAT', 'NULLABLE', None, (), None),
 SchemaField('y_coordinate', 'FLOAT', 'NULLABLE', None, (), None),
 SchemaField('year', 'INTEGER', 'NULLABLE', None, (), None),
 SchemaField('updated_on', 'TIMESTAMP', 'NULLABLE', None, (), None),
 SchemaField('latitude', 'FLOAT', 'NULLABLE', None, (), None),
 SchemaField('longitude', 'FLOAT', 'NULLABLE', None, (), None),
 SchemaField('location', 'STRING', 'NULLABLE', None, (), None)]

In [24]:
num_timestamp_fields = 2 # Put your answer here

q_2.check()

Correct

For a hint or the solution, uncomment the appropriate line below.

In [25]:
#q_2.hint()
#q_2.solution()

### 3) Create a crime map

If you wanted to create a map with a dot at the location of each crime, what are the names of the two fields you likely need to pull out of the `crime` table to plot the crimes on a map?

In [26]:
# Write the code here to explore the data so you can find the answer

In [27]:
# Write the code here to explore the data so you can find the answer
client.list_rows(table, max_results = 3).to_dataframe()

,unique_key,case_number,date,block,iucr,primary_type,description,location_description,arrest,domestic,...,ward,community_area,fbi_code,x_coordinate,y_coordinate,year,updated_on,latitude,longitude,location
0,26773,JF247428,2022-05-18 10:06:00+00:00,002XX W 105TH ST,0110,HOMICIDE,FIRST DEGREE MURDER,HOUSE,True,True,...,34,49,01A,1176555.0,1835314.0,2022,2022-09-18 04:45:51+00:00,41.703447,-87.629105,"(41.703447034, -87.629104948)"
1,4638,HP461457,2008-07-19 12:35:00+00:00,105XX S WENTWORTH AVE,0110,HOMICIDE,FIRST DEGREE MURDER,PORCH,False,False,...,34,49,01A,1176812.0,1835178.0,2008,2022-08-31 04:51:30+00:00,41.703068,-87.628168,"(41.703068059, -87.628167951)"
2,25850,JE190772,2021-04-06 01:55:00+00:00,105XX S MARYLAND AVE,0110,HOMICIDE,FIRST DEGREE MURDER,STREET,False,False,...,9,50,01A,1183774.0,1835238.0,2021,2022-08-31 04:51:30+00:00,41.703073,-87.602673,"(41.703073446, -87.602673084)"

For a hint or the solution, uncomment the appropriate line below.

In [28]:
fields_for_plotting = ['x_coordinate', 'y_coordinate'] # Put your answers here

q_3.check()

`'latitude'` and `'longitude'` would be better and more standard than `'x_coordinate'` and `'y_coordinate'`, but this might work.

Correct

Thinking about the question above, there are a few columns that appear to have geographic data. Look at a few values (with the `list_rows()` command) to see if you can determine their relationship.  Two columns will still be hard to interpret. But it should be obvious how the `location` column relates to `latitude` and `longitude`.

In [29]:
# Scratch space for your code

# Keep going

You've looked at the schema, but you haven't yet done anything exciting with the data itself. Things get more interesting when you get to the data, so keep going to **[write your first SQL query](https://www.kaggle.com/dansbecker/select-from-where).**

---




*Have questions or comments? Visit the [course discussion forum](https://www.kaggle.com/learn/intro-to-sql/discussion) to chat with other learners.*